### PR TITLE
General UI Update

### PR DESCRIPTION
**Pull request by charleshkang**
- UI in storyboard is updated
- added Roboto font and changed all fonts to Helvetica or Roboto to be consistent
- changed name of storyboard identifiers to be consistent
- removed `!` from `prepareUIwithCard`

### CODE REVIEW

**Comment by vhart** [comment]
not a huge fan of the positioning of the question and the buttons underneath it. Doesn't seem intuitive. Also we should get rid of the alert controller. It'll get annoying real fast, having it pop up after every question. Instead, user initiated buttons could be present where they click it if got it right or not. Idk what do you guys think @charleshkang @mesbekmek ?

**Comment by charleshkang** [comment]
Yeah, I forgot that we sometimes show images with the question and didn't consider that when wireframing...Need to think of a better layout for that screen.

I agree with removing the alert controller, even when running the app to see my changes, it got annoying pretty quick. Will try and think of a better way to handle right&wrong answers

**Comment by mesbekmek** [comment]
@vhart I agree, user initiated buttons sounds good. Were you thinking these buttons would be always visible and at the bottom of the screen?

**Comment by vhart** [comment]
@mesbekmek yep, spot on dude. Any objections?

**Comment by mesbekmek** [comment]
Nope, sounds good to me!

**Comment by charleshkang** [comment]
Let me know what you guys think of the new mock-ups. 





I personally like putting the right/wrong button on the answerVC, since the user will go there anyway to check their answer. No need to make them check their answer, then come back to the questionVC to press whether they were right/wrong. 

On the answerVC, the user would be shown the next question if they get it right, and if they get it wrong, display an alert controller saying "you'll get it next time! do x things to try and solve it", or just show them the same question to try again.

The reason I put the image on top of the question is that it's a static size, but all the questions differ in length. Just seems easier to put it under the image

I was also thinking we could to a Tinder style swiping implementation, where you swipe left/right depending on if you got the question right/wrong, as well as an answer button in the center.

**Comment by mesbekmek** [comment]
@charleshkang I like the new UI mock up, good job! I also like the tinder like swipe functionality

**Comment by vhart** [comment]
@charleshkang looks good. The first one is strange since it has the `check answer` `I got it right` and `I got it wrong` on the same screen. But the others make sense. Maybe the wording could be improved but it looks good.

**Comment by vhart** [comment]
Closing due to inactivity

**Pull request closed without merging**
