### PR TITLE
Swift 3 Update

### PR DESCRIPTION
**Pull request by vhart**
Updated project file and Pods to swift 3. Fixed spec failures related to the upgrade and other syntax issues. Also updated our Firebase code to work with the latest version of Firebase. Works now.

@mesbekmek @charleshkang

### CODE REVIEW

**Comment by vhart** [comment]
I wouldnt read through the changes for this one. maybe just pull it down and run it to make sure its okay.

**Comment by charleshkang** [comment]
great! sorry i haven't been as active, will look to open up pr's soon.

**Comment by charleshkang** [comment]
@vhart project runs fine. i'm wondering why the answerVC is back to obj-c though, i'm pretty sure i converted all view controller classes to swift, albeit 2.3 :/ shouldn't be a huge issue though

**Review by charleshkang — APPROVED** [review]
everything works fine, i'd like to open another PR for the UI update again

**Comment by vhart** [comment]
thanks for the merge @charleshkang

**Pull request merged**
