### PR TITLE
UI update

### PR DESCRIPTION
**Pull request by charleshkang**
simple UI update to the first screen, checked out my old mock-ups for the following screens and need to rethink what they should look like. 

also updated the fonts to be avenir heavy on the questionVC! 

not sure what's up with the `podfile` changes, but that happened after i did `pod install` 

ifc_home
ifc_questions

### CODE REVIEW

**Comment by vhart** [comment]
@charleshkang can you tie down the pods in the podfile to their swift 3.0 stable branch? And then run the tests and project to make sure it works.

**Comment by vhart** [comment]
@charleshkang and also if you can leave a screenshot of the updated screens 👍

**Comment by charleshkang** [comment]
@vhart will do the screenshots, but not sure what you mean by "tie down the pods in the podfile to their swift 3.0 stable branch"

**Comment by vhart** [comment]
@charleshkang so you find out which branch is 3.0 compatible. then you tie the pod to that version like :
```
pod 'AFNetworking', '~> 1.0'
```

**Comment by vhart** [comment]
this way we always use the same version on each build

**Comment by charleshkang** [comment]
so `pod 'BrightFutures', '~> https://github.com/Thomvis/BrightFutures/tree/swift3.0'`?

**Comment by charleshkang** [comment]
this is what the `podfile` looks like now: 

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ‘InterviewFlashCards’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'BrightFutures', git: 'https://github.com/Thomvis/BrightFutures', branch: 'swift3.0'
   pod 'SwiftyJSON', '3.0.0'
   pod 'SyntaxKit', git: 'git@github.com:vhart/SyntaxKit', branch: 'master'

  # Pods for InterviewFlashCards
  target 'InterviewFlashCardsTests' do
    pod 'Quick'
    pod 'Nimble'
    pod 'Nocilla'
  end
end
```

i get a bunch of warnings related to BrightFutures after tying it to the swift 3 branch

**Comment by vhart** [comment]
@charleshkang you can remove bright futures since we didnt use it

**Comment by vhart** [comment]
@charleshkang im also not sure we used SwiftyJSON, but don't quote me on that

**Comment by charleshkang** [comment]
edit: @vhart, yeah you use SwiftyJSON in `Flashcard.swift`, and so is BrightFutures

screen shot 2017-04-21 at 1 47 45 pm

any idea how to resolve this? have done all the basics and it's definitely in our podfile

**Comment by vhart** [comment]
@charleshkang try a clean and build?

**Comment by vhart** [comment]
oh but syntaxkit isnt in the test target

**Comment by charleshkang** [comment]
have done that, restarted xcode, and deleted derived data

**Comment by charleshkang** [comment]
where should i go from here? 

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ‘InterviewFlashCards’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'BrightFutures', git: 'https://github.com/Thomvis/BrightFutures', branch: 'swift3.0'
   pod 'SwiftyJSON', '3.0.0'
   pod 'SyntaxKit', git: 'git@github.com:vhart/SyntaxKit', branch: 'master'

  # Pods for InterviewFlashCards
  target 'InterviewFlashCardsTests' do
    pod 'Quick'
    pod 'Nimble'
    pod 'Nocilla'
    pod 'SyntaxKit'
  end
end
```

**Comment by charleshkang** [comment]
going to push what i have for now, maybe you can take a look at it

**Comment by charleshkang** [comment]
@mesbekmek @vhart if one of you could approve the quick UI update, that'd be great

**Comment by charleshkang** [comment]
@vhart @mesbekmek can someone please check this out really quickly and approve it when they get a chance?

**Comment by mesbekmek** [comment]
@charleshkang I get the UI updates but what about all the other files that were modified or added?Are those safe to merge?

**Comment by charleshkang** [comment]
@mesbekbek i just took a look at the files that i changed and it should be fine to merge.

**Review by mesbekmek — APPROVED** [review]

**Pull request merged**
